"""Run inside Blender: execute the Python fixes suggested by `blender-quality describe`, then save a copy.

The snippets come from this repository's own describe.py (trusted test input), never from a scene.
Usage: blender ... scene.blend --python apply_fixes.py -- FIXES.json OUTPUT.blend
"""

import json
import sys

import bpy

fixes_path, output = sys.argv[sys.argv.index("--") + 1 :][:2]
with open(fixes_path, encoding="utf-8") as handle:
    snippets = json.load(handle)
for snippet in snippets:
    exec(snippet, {"bpy": bpy})  # noqa: S102 - generated by describe.py in the test itself
bpy.ops.wm.save_as_mainfile(filepath=output, copy=True)
print(f"APPLIED {len(snippets)} fixes")
